### ISSUE TITLE
help for AD authentication

### ISSUE THREAD

**Issue by geo782** [heiglandreas/authLdap#181]
Hi, 
Im trying to setup the plugin so registered users in wordpress can login if exist in active directory.
For ldap url, i spoke to our server admin and gave me the following url to use:
ldaps://myusername:mypassword@10.XX.XX.XXX:636 (or ldap:// with other port), but im getting LDAP authentication failed with exception (ldap url) does not provide a search-base. The same message if I try this url ldap://uid=Firstname Lastname,OU=Common Users OU,OU=RDP enabled Users OU,OU=Operator Users ,DC=mydomain,DC=com:secret@servername:port/DC=mydomain,DC=com.
I tryed telnet and I can connect! Im I missing something?

Regards
George

**Comment by heiglandreas** [comment]
Would you mind sending me (sanitized) screenshots of the configuration?

**Comment by geo782** [comment]
Thank you for the reply, I have sent plugin configuration with email!
Regards
George

**Comment by heiglandreas** [comment]
Thanks! Received it.

From what I can see immediately you might need to adapt the searchfilter to something like "(sAMAccountName=%1$s)"

But that seems not to be the main issue here.

The error-message you reported looks like your LDAP-URI is missing the path-component. That path-component defines the Base-DN from which all searches start. According top your information it should look something llike this:

   ldaps://myusername:mypassword@10.XX.XX.XX:636//DC=mydomain,DC=com

You also tried a more verbose URL but there seem to be spaces in that. Did you URL-Encode them? So that hit looks like this:
 
    ldap://uid=Firstname%20Lastname,OU=Common%20Users%20OU,OU=RDP%20enabled%20Users%20OU,OU=Operator%20Users,DC=mydomain,DC=com:secret@10.XX.XX.XX:389/DC=mydomain,DC=com

Please test these options and then get back to me. Perhaps with a (sanitized) excerpt from the Log-Files...

**Comment by geo782** [comment]
Thanks for the reply,
Regarding the filter, wouldn't be better if i use (|(uid=%1$s)(mail=%1$s)) since i have to search username or email that is used to login to wordpress?

I have tested both ldap uri and when i use login user "test1", both give the following in the debug.log 

```
User '' logging in
Username not supplied: return false
User 'test1' logging in
about to do LDAP authentication
connect to LDAP server
LDAP authentication failed with exception: bind was not successfull: Can't contact LDAP server.
```

**Comment by heiglandreas** [comment]
Did you resolve the issue yet?

And yes: You are right to better use that combined filter. But AD has (IIRC) no uid-attribute but a sAMAccountName attribute. But you better confirm that with your AD-Admin

**Comment by geo782** [comment]
Yes, its the sAMAccountName, you are correct. Also our problem solved by our admin, thank you for the information :)

**Comment by heiglandreas** [comment]
Great to hear ;-)
