### ISSUE TITLE
Connection with their own user

### ISSUE THREAD

**Issue by Markel** [heiglandreas/authLdap#213]
Hi!

¿Is there anyway to use the username and password provided by the users in the _LDAP URI_ as "admin user"? In the case of the LDAP server that I'm using my account isn't configured to see the details of other users (apart from the simplest ones like the uid) so I cannot fill the gaps like email or name (the plugin creates the account anyway but it is a relatively empty account). Obviously I can see all the details of my own account, so I was wondering if something similar to what we can do in the filter option could be done. An example:

ldap://uid=**%s**,dc=example,c=com:**%p**@ldap.example.com/dc=basePath,dc=example,c=com

I've checked the source code and it doesn't seem like it.
Thank you!

**Comment by heiglandreas** [comment]
Hey @Markel. Thanks for raising this issue.

Currently what you ask for is not provided mainly due to one reason:

The user-part of the URL (the `uid=%s,dc=example,dc=com`-part) can change depending on the user and depending on how the LDAP server is structured. In your case it might be `uid=markel,dc=deptA,dc=example,dc=com` but for someone else it might be `uid=userb,dc=deptB,dc=example.dc=com` so we can not really hardcode that or need much more information.

To circumvent that we need a way to retrieve this so called Distinguished Name (DN) from the LDAP-Server itself. That's why this plugin uses one dedicated admin-user to first do a search throughout the LDAP for an entry with the specified information - like `uid=userB` to then use that users DN for the login. 

If I recall correctly we aer actually using that users login to retrieve the additional information like username email-address etc though I would need to check whether that is correct. If that's not the case I could think about adding a switch to either use the users account to get that information or the admin account. That might circumvent that issue.

Nevertheless should you think about using a dedicated separate user for the Admin-access that is not able to read your password or other information that should not be shared with the public. You should check with your LDAP-Admin for that! It makes the whole thing much more secure and your account not vulnerable for exposure.
