### ISSUE TITLE
First name change on logon

### ISSUE THREAD

**Issue by mikibarzilay** [heiglandreas/authLdap#228]
Hello,
I created (manually) a WordPress user named mickyb and specify first name and last name.
Once I'm login with 'mickyb' the authLdap set it to the username 'mickyb'.

I'm attaching screenshots to indicates the issue.

Please advise
Micky
![2022-07-13_22-09](https://user-images.githubusercontent.com/10675448/178813749-2c516258-300c-4d2a-9c69-4bff9ed97763.png)
![2022-07-13_22-10](https://user-images.githubusercontent.com/10675448/178813763-b8c313af-72f0-4490-9e83-198249cd8c2b.png)
![2022-07-13_22-10_1](https://user-images.githubusercontent.com/10675448/178813779-164910bf-3266-468d-b6d4-0b103fa1b4c8.png)

**Comment by heiglandreas** [comment]
Hey Micky.

Thanks for reaching out.

To be able to debug this and give you advice I'd need the configuration of authLdap and an excerpt of your user from the LDAP.

In general the plugin is intended to use the LDAP as single source of truth. So informations from the LDAP will overwrite the info in WordPress. That usually makes it easier to maintain everything in one place and not having to change things in different places.

But that should also have overwritten the last name. That's why it would be helpful to have the infos to be able to check what exactly is happening...

**Comment by mikibarzilay** [comment]
Dear Andreas,
In the Active Directory the First Name and Last name are accurate and same as I set manually in WordPress.
However, the authLdap is replacing the First Name and set the User Name as First Name.

I'm attaching the authLdap configuration and the Active Directory properties for mikcyb (the username).

I'm going to appreciate your support.

Micky
![image](https://user-images.githubusercontent.com/10675448/178838288-e3079231-33ed-4522-b0e3-b0396f8dd3ee.png)
![image](https://user-images.githubusercontent.com/10675448/178838355-08f16039-ca37-4ace-90e5-e6ca72e7405e.png)
![image](https://user-images.githubusercontent.com/10675448/178838400-ed7f9611-4b53-4bc5-bb93-2a7ec1fa2c28.png)
![image](https://user-images.githubusercontent.com/10675448/178838420-d33603c3-89ed-4975-a45f-bc10ae3a6463.png)
![image](https://user-images.githubusercontent.com/10675448/178838451-a91cbf1f-3de2-4432-82d8-9e376406d281.png)

**Comment by mikibarzilay** [comment]
Solved by setting GivenName in authLdap instead of SamAccountName.

**Comment by heiglandreas** [comment]
Good to see that you solved it! Thanks for the feedback!
