### ISSUE TITLE
No bind successfull. Exception thrown in line 71

### ISSUE THREAD

**Issue by Dominique-Wellisch** [heiglandreas/authLdap#229]
Hi,

I tried to setup the plugin this is the error:
![image](https://user-images.githubusercontent.com/99669443/200804090-323a1c8d-b5b3-4c63-b942-9a81f4d4f4cf.png)
Settings:
![image](https://user-images.githubusercontent.com/99669443/200804170-849f0017-10d8-4338-90e9-04dc639efc63.png)
Filter: (sAMAccountName=%s)
Url:ldap://CN=LDAP-Wordpress,CN=Users,DC=bt,DC=loc:MYSUPERSTRONGPASSWORD@DC1/DC=bt,DC=loc.

**Comment by heiglandreas** [comment]
From a first look it seems to be an issue with the server-name. Could it be that you need to add the full DNS-name instead of the `DC1`? So something like `DC1.bt.loc`...

To test that, try something like `ping DC1` on the console of the webserver. It you do not get the IP-Address of the server back you need to be more specific in the LDAP-URI.

A second thought is to check whether your `MYSUPERSTRONGPASSWORD` contains some special characters that might need to be URL-encoded. Especially something like `@` or `"` or `/` or `:`. URL-encode the password to be on the safe side.

**Comment by Dominique-Wellisch** [comment]
I am using the IP for the server and the password contains only letters and numbers.
I just changed it for the screenshot.

**Comment by heiglandreas** [comment]
OK. Thanks.

So it still looks like the main account you are using is not able to bind to the LDAP.

So something with the `CN=LDAP-Wordpress,CN=Users,DC=bt,DC=loc:MYSUPERSTRONGPASSWORD@DC1/DC=bt,DC=loc` seems to not be OK.

Do you have access to a command-line on the webserver the blog is running on? I'd recommend trying the LDAP-URI with a tool like `ldapsearch`. Alternatively you can use a GUI on your machine to check whether the credentials are OK. Something like Apache DirectoryStudio. When you get the login up and running on that tool, then you should also be able to connect via the LDAP-URI.

If that doesn't work out, I might need some more information about the LDAP-Schema. If you could send me some informations about that Wordpress-user I might be able to tell you a bit more. Feel free to send it directly to the email-address on my profile :wink:

**Comment by Dominique-Wellisch** [comment]
ldapsearch -x -b "OU=USR,DC=bt,DC=loc" -H ldap://10.10.50.11  -D "CN=LDAP-Wordpress,CN=Users,DC=bt,DC=loc" -W
This ldapsearch works.
Also the vm which is hosting wordpress is a ubuntu server, which is joined to our active directory.
LDAP-schema is a active directory.

**Comment by heiglandreas** [comment]
Can you send me the stack trace of the error message? I am a bit irritated as the line numbers seem to be off towards my source code...

**Comment by heiglandreas** [comment]
I assume that you got your LDAP authentication sorted. If you still got issues with this plugin feel free to open a new issue.
