### ISSUE TITLE
bug fix for authLdap_login

### ISSUE THREAD

**Issue by chaplina** [heiglandreas/authLdap#52]
Line 178 and 179 should be changed to:

 $authLDAPGroupEnable    = get_option('authLDAPGroupEnable', false);
 $authLDAPGroupOverUser  = get_option('authLDAPGroupOverUser', false);

If those options were never checked in the AuthLDAP settings page they are not saved to the DB and thus their default values should be false.

**Comment by chaplina** [comment]
If you want options saved to the DB when the plugin is activated, look at the Wordpress function register_activation_hook.

**Comment by EmTeedee** [comment]
These options are new and behaviour of previous versions of the plugin was the same as if these options are true, that's why this is the default.

**Comment by chaplina** [comment]
As I mentioned, if the options are never checked in the settings page, they 
are not saved to the DB.

Thus, if someone does not want to use groups, they will not check those 
options, and the DB will not contain those options.  BUT, get_option will 
use the default setting because the option is not in the DB, and thus the 
plugin's expected behavior, per the settings page, will NOT be followed.

IMHO, the best way to get rid of these default values for options is to 
initialize all of the variables to a default value when the plugin is 
activated.  That will store all variables used by the plugin in the DB.

**Comment by EmTeedee** [comment]
First, yes, it would be better to write default values with the activation hook, I don't do much Drupal development, so I don't know the conventions well.

The current behavior shouldn't be a problem though. The option page also uses the dame default values (lines 75/76). So for someone who upgrades, the plugin will behave as before (because of the defaults in lines 178/179) and when they eventually go to the settings page, the options will be checked (because of lines 75/76). So all is well.
A new user will see them both checked when they set the options too.
Lines 53/54 are a little confusing, but we only get a value (of 1) back from the form if the option is checked and nothing if it's unchecked (hence the false there).

Alas, activation hook would be better and less confusing, so I'll try to add that in the next couple of days.

**Comment by heiglandreas** [comment]
Excellent idea! (Thought so 24 days ago, but didn't get to saying so)

**Comment by EmTeedee** [comment]
Sorry for the long delay, I read through wordpress docs and found that there is no hook that is called on a plugin update. The activation hook used to be called but not anymore.
The solution proposed by wordpress would be to version the configuration and every time the plugin is loaded to check whether the stored config is the same version as the plugin's.
Since this plugin is not in a class, we would need to hook plugins_loaded and check there.

**Comment by heiglandreas** [comment]
Fixed with #58
