### ISSUE TITLE
Manual control of Wordpress Roles?

### ISSUE THREAD

**Issue by wunc** [heiglandreas/authLdap#69]
The current behavior with authLdap 1.4.8 on WordPress 4.3 is:

1. A new User logs in via LDAP and they are added with the "Default Role" as defined in the authLdap settings
2. An administrator manually changes that user's role to something else
3. The next time that user logs in, their role is reset to "Default Role"

I cannot find a way to manually control (via WP dashboard > Users > edit) the WP roles of users that are authenticated via LDAP. They always revert to the "Default Role" on login. I do not want to map LDAP Groups to WP roles, as I do not have access to change their LDAP groups, so I have unchecked that option in the authLdap settings.

Is this intended behavior? Is there a way to disable step 3 above? Can we make "Default Role" only for _new_ users, not existing ones?

**Comment by heiglandreas** [comment]
yes we can! And we should! I'll have to check the code to see what's going on internaly though. I'll be back with you ASAP.

**Comment by heiglandreas** [comment]
Just to make sure I understood you right: As an administrator you are not able to alter the role of an LDAP-authenticated user on that users profile-page (wp-admin/user-edit.php?user_id=[user-id])? Because you should be. This plugin only removes the password-fields in that dialog as passwort-changing doesn't make any sense for LDAP-authenticated users.

It might be possible that a checked field ```LDAP Groups override role of existing users?``` causes that a role that has been changed by an administrator is reset to the default. But if that happens **and the above field is unchecked** it's definitely a bug!

Would you be so kind to check that and get back with what you've found? That would be really helpful!

Thanks!

**Comment by wunc** [comment]
Sorry, to clarify, what I'm seeing is this: An administrator _can_ change the role of an LDAP-authenticated user. However, that change is only good until that user logs out and back in again. When they log in a second time, their role is reverted back to the `Default Role` as defined in the authLdap settings.

The settings `LDAP Groups override role of existing users?` and `Map LDAP Groups to wordpress Roles?` are both unchecked. In the database wp_options table, `authLDAPGroupEnable` and `authLDAPGroupOverUser` both have blank `option_value`.

**Comment by wunc** [comment]
Okay, I figured it out. Line 431 of authLdap.php:

```php
$meta_value = $wpdb->get_var("SELECT meta_value FROM {$wpdb->usermeta} WHERE meta_key = 'wp_capabilities' AND user_id = {$uid}");
```

This assumes that the prefix is `wp_`, but I am using a custom prefix for my wordpress database. Changing it to

```php
$meta_value = $wpdb->get_var("SELECT meta_value FROM {$wpdb->usermeta} WHERE meta_key = '{$wpdb->prefix}capabilities' AND user_id = {$uid}");
```

fixes the problem.
