### ISSUE TITLE
Add new users to the Groups instead of to the Roles

### ISSUE THREAD

**Issue by martinjinda** [heiglandreas/authLdap#74]
If you have a own Groups you can't add them to these Groups. You can add them only into Role (Editor, Subscriber, etc.). How it's possible to add them by this plugin?

We already have a plugin for sorting new users, but it's working only for default register by WP. How can we hook this code to AuthLDAP?

```
function ataccama_permissions_setUserPermissions($userID){
    global $wpdb;
	$textOutputOfficial = "";
	$textOutput = "";
	$textOutputAtaccama = "";
	// get user email
	$user = get_user_by( 'id', $userID);
    $user_email = $user->user_email;
	// if NOT TEST_MODE push new membership to DB
	if(!TEST_MODE)
	{
		// define groups
		$groups= array(
					"11" => "",
					"12" => "Group 1",
					"16" => "Group 2",
					"13" => "Group 3",
					"14" => "Group 4",
		 );
		$domain = explode('@', $user_email);
		$granted = false;
		$group_text = "";
		// get ID of groups were domain is regidtered
		$gids = $wpdb->get_results( "SELECT group_id FROM wp_pp_domain_group WHERE domain LIKE '".$domain[1]."'");

		if (empty($gids))
		{
			$granted = false;
		}
		else
		{
			// setting up membership
			foreach ( $gids as $gid )
			{
			  $result = $wpdb->insert(
				 'wp_pp_group_members',
				 array(
				   'group_id'		=> $gid->group_id,
				   'user_id'		=> $userID,
				   'member_type' 	=> 'member',
				   'status' 		=> 'active',
				   'add_date_gmt' 	=> '2014-10-15 12:35:44',
				   'date_limited' 	=> '0',
				   'start_date_gmt' => '0000-00-00 00:00:00',
				   'end_date_gmt' 	=> '2035-01-01 00:00:00'
				 ),
				 array(
						'%d',
						'%d',
						'%s',
						'%s',
						'%s',
						'%d',
						'%s',
						'%s')
				);
			  // group text forming
			  $group_text .= $groups["$gid->group_id"].", ";
			}
			$granted=true;
		}

		$textOutput .= " (".trim($group_text, ", ").")";
		if ($textOutput == " ()")
		{
			$textOutputOfficial .= "";
		}
		else
		{
			$textOutputOfficial .= $textOutput;
		}
		$textOutputAtaccama .= trim($group_text, ", ");
	}
	$textVars = array(
			'textOutputAtaccama'	=> 	$textOutputAtaccama,
			'textOutputOfficial'	=> 	$textOutputOfficial
	);
	// send verification email
	ataccama_permissions_sendNotificationAboutMembership($user_email, $granted, $textVars);

}

```

**Comment by heiglandreas** [comment]
@martinjinda As far as I see it it's as follows:

Wordpress currently supports roles but not groups. You have a plugin that allows wordpress to use groups instead of roles and which adds a newly created user to a group. 

As I wouldn't want the authLDAP-Plugin to integrate with every single group-plugin that's out there (that would be far to much effort) I could think of adding a wordpress-hook to authLDAP which you could use to trigger expected behaviour.

Or perhaps the existing ```authenticate```-filter might be usefull. That's the filter authLdap hooks into and creates the new user. On hooking into that filter **after** authLDAP (so with anything from 11 on as priority) you'd be able to get the result from authLdap and pass that on to a custom function. Beware that authLDap return a WP_User-object, not a user-id!

**Comment by heiglandreas** [comment]
We've sorted this out on gitter. So I close it here.
