### ISSUE TITLE
Always white screen after login and debug not working. why???

### ISSUE THREAD

**Issue by frottoli** [heiglandreas/authLdap#76]
Hello.
I'm totally new in wordpress and LDAP Authentication and it's a few days that I'm tryng to configure my wordpress website to login through my domain controller via authLDAP.

The name of my DC is itbgw2k12dc01(192.168.20.9) and my domain is vittoria.local.
With a LDAP browser I can browse correct into my DC via LDAP after I installed the feature AD LDS on it. Here an image:
![ldap1](https://cloud.githubusercontent.com/assets/14542534/10046727/caef8f44-620a-11e5-8065-aca803610795.jpg)
![ldap2](https://cloud.githubusercontent.com/assets/14542534/10046789/1cb9fbb6-620b-11e5-9b90-cce0dc00eb55.jpg)

Following the suggested syntax I inserted ad LDAP uri: 
ldaps://administrator:******@itbgw2k12dc01.vittoria.local/DC=vittoria,DC=local

ldaps because I need to use SSL (already tried without with the same result)
First question... IS THE URI CORRECT BASING ON THE IMAGE I POSTED?
If I active the LDAP login and I try to type credentials I get a white screen and I cannot login anymore into backend. I have to restore wordpress to the previous modifications.
but... if the URI is incorrect, shouldn't the debug help me?

Please let me know if you have any Idea. 
Thanks a lot,
Fabio.

**Comment by heiglandreas** [comment]
Hi Fabio. The URI looks correct from what I can tell as you are using Active Directory as backend. Otherwise you'd have to replace the "administrator" with the complete DN. 

But much more important is the question where your error-log is written to. Activating the debugging will add some verbose information to the default error-log of your webserver. But if the screen stays white that usually means that an error occured. That would also be logged into the error-log. From what you wrote I couldn't tell whether you already looked there or not. Would you be so kind to check that please?

**Comment by frottoli** [comment]
First of all thank you so much for the quick answer!
Where I can find the error log? 

Thanks,

Fabio.

**Comment by heiglandreas** [comment]
Three things: 

1. the authLdap-plugin needs the LDAP-extension for PHP to be available. Do you have the possibility to check that using ```phpinfo()```? 
2. It looks like you should be using ```vittoria\administrator``` as login-name instead of ```administrator``` 
3. It depends very much on your server-setup where to look for the log-files. Are you running on apache httpd or on nginx or on IIS? If it's a linux-system you are running the webserver on, chances are great to have the log-files in a folder like ```/var/log/apache2``` or ```/var/log/nginx```. If you're on a windows-machine I assume the logfiles are somehow available via the managementconsole. But I sadly have to admit that I can't give you more information on that one :frowning: You should check whether you can get someone from your IT to give you a hand...

**Comment by frottoli** [comment]
Problem Found!

the LDAP extension line in php.ini was commented! I thought was enabled by default... instead was disabled. 
I solved searching on google.

Anyway many thanks for the quick and detailed help!

**Comment by heiglandreas** [comment]
You're welcome! So can we close this issue? Or are there other questions open? (You are always free to reopen this or create a new issue!)

**Comment by frottoli** [comment]
we can close it.
Thanks a lot again!
