### ISSUE TITLE
CAS / SSO

### ISSUE THREAD

**Issue by Kzou** [heiglandreas/authLdap#77]
Hi,

do you think it possible to integrate a CAS module (as phpCAS) ?

authLDAP is perfect with Groups ldap for Roles WP!

Thanks

**Comment by heiglandreas** [comment]
Hi @Kzou. When I understand that right you are refering to a CentralAuthenticationSystem. 

In my eyes that would be a separate plugin as the users shall log into wordpress *either* using LDAP *or* using CAS as backend. You could allow both by activating an LDAP plugin *and* a CAS-plugin and depending on the first match it would log in using either of the two methods.

And yes, it would be better to separate the authorization-part (setting a group for the user) of authLDAP into a separate plugin so that you could use a CAS-plugin to authenticate and a (not yet existing) LDAP-Group-plugin to authorize the user.

That somehow would make sense even though I'm not yet completely sure on how to do that. I'll give that one a thorough thought!

**Comment by Kzou** [comment]
Hi @heiglandreas 

thank you for your answer :)
indeed, at first I thought to use another plugin..

but the connection must be transparent for users:
the user must connect from the CAS, and if he's not in WordPress database, so creates it with the LDAP informations.

I don't know if it's possible..

**Comment by heiglandreas** [comment]
It's (more or less) possible, has some gotchas though.

The authentication should work in a way that the ```authenticate```-filter is called on login of a user. Each plugin implementing that filter should either return a user-object when authentication succeeded within that plugin or an error if authentication did not succeed. Therefore a plugin that gets a user-object does not need to authenticate further as the user already has been authenticated by another plugin but just return that user-object.

Therefore the order in which the plugins are called is important. For you that order would be

 # CAS
 # LDAP
 # Local Database

But as the order is hard-coded in the plugin that is not that easy. I was already thinking about a plugin that checks for authentication-plugins and allows you to change the order.

**Comment by heiglandreas** [comment]
Hey @Kzou - any news on this issue? I'll close it for now but if you have more issues please reopen it!
