### ISSUE TITLE
Stop Password-Change Email on password-Update via LDAP

### ISSUE THREAD

**Issue by heiglandreas** [heiglandreas/authLdap#80]
Currently a user will get an Email after login that the password has changed when password-caching is enabled. The preffered behaviour would be to simply not send a password-change-Email when a user-password is changed via LDAP.

THis has been reported on https://wordpress.org/support/topic/authldap-authentication-triggers-email-password-change-notification

**Comment by litinoveweedle** [comment]
Hi heiglandreas,

I was able to solve the problem with this code patch:

<pre><code>
--- /tmp/authldap/authLdap.php	2015-10-12 14:04:20.000000000 +0200
+++ authLdap.php	2015-10-15 17:49:11.293313267 +0200
@@ -150,6 +150,10 @@
         return $user;
     }
 
+    if (isset($user) && $user->ID) {
+        return $user;
+    }
+
     authLdap_debug("User '$username' logging in");
 
     if ($username == 'admin') {
@@ -261,13 +265,13 @@
             return false;
         }
 
-        $uid = authLdap_get_uid($realuid);
+        $wp_user = get_user_by( 'login', $realuid );
         $role = '';
 
         // we only need this if either LDAP groups are disabled or
         // if the WordPress role of the user overrides LDAP groups
         if (!$authLDAPGroupEnable || !$authLDAPGroupOverUser) {
-            $role = authLdap_user_role($uid);
+            $role = authLdap_user_role($wp_user->ID);
         }
 
         // do LDAP group mapping if needed
@@ -338,18 +342,20 @@
         }
 
         // optionally store the password into the wordpress database
-        if (authLdap_get_option('CachePW')) {
-            $user_info['user_pass'] = wp_hash_password($password);
-        } else {
+        if (! authLdap_get_option('CachePW')) {
             // clear the password
-            $user_info['user_pass'] = '';
+            $password = '';
+        }
+        if ( $wp_user->ID && ! wp_check_password( $password, $wp_user->data->user_pass, $wp_user->ID) ) {
+            error_log('[AuthLDAP] ' . 'Password change ' . $realuid .' '.$wp_user->ID. ' '.$wp_user->data->user_pass, 0);
+            $user_info['user_pass'] = $password;
         }
 
         // add uid if user exists
-        if ($uid) {
+        if ($wp_user->ID) {
             // found user in the database
             authLdap_debug('The LDAP user has an entry in the WP-Database');
-            $user_info['ID'] = $uid;
+            $user_info['ID'] = $wp_user->ID;
             unset ($user_info['display_name'], $user_info['nickname']);
             $userid = wp_update_user($user_info);
         } else {
@@ -383,33 +389,6 @@
     }
 }
 
-/**
- * Get user's user id
- *
- * Returns null if username not found
- *
- * @param string $username username
- * @param string user id, null if not found
- */
-function authLdap_get_uid($username)
-{
-    global $wpdb;
-
-    // find out whether the user is already present in the database
-    $uid = $wpdb->get_var(
-        $wpdb->prepare(
-            "SELECT ID FROM {$wpdb->users} WHERE user_login = %s",
-            $username
-        )
-    );
-    if ($uid) {
-        authLdap_debug("Existing user, uid = {$uid}");
-        return $uid;
-    } else {
-        return  null;
-    }
-}
-
 /**
  * Get the user's current role
  *
</code></pre>

The original problem is, that BOTH wp_insert_user and wp_update_user DO hash password, so it should be provided from `authLdap_login` in clear text format. Otherwise you will hash it twice! This also means, that the whole 'CachePW' was faulty, as wrong value of double hashed password was saved.

So once I clear this` $user_info['user_pass'] = wp_hash_password($password);` from code it was OK. But anyway I would maybe suggest using WP_user object through whole `authLdap_login` function and updating directly previously fetched or created object via new `WP_user()`.

I will post rework ASAP.

Kind regards
Litin

**Comment by litinoveweedle** [comment]
Hi heiglandreas,

there were some additional issue with some new conditions, it seems to be fixed now. Also I would probably not go for working directly over WP_User object, as setting object attributes via __set require WP > 3.3. so it would decrease compatibility of your plugin. (I have still something in my mind but for now I just needed plugin to be functional :-) Please test it and let me know, if this version is fine for you.

BR
Litin

<pre><code>
--- /tmp/authldap/authLdap.php	2015-10-12 14:04:20.000000000 +0200
+++ authLdap.php	2015-10-15 19:41:55.537774822 +0200
@@ -150,6 +150,10 @@
         return $user;
     }
 
+    if (isset($user) && $user->ID) {
+        return $user;
+    }
+
     authLdap_debug("User '$username' logging in");
 
     if ($username == 'admin') {
@@ -261,13 +265,13 @@
             return false;
         }
 
-        $uid = authLdap_get_uid($realuid);
+        $wp_user = get_user_by( 'login', $realuid );
         $role = '';
 
         // we only need this if either LDAP groups are disabled or
         // if the WordPress role of the user overrides LDAP groups
-        if (!$authLDAPGroupEnable || !$authLDAPGroupOverUser) {
-            $role = authLdap_user_role($uid);
+        if ((!$authLDAPGroupEnable || !$authLDAPGroupOverUser) && isset($wp_user->ID)) {
+            $role = authLdap_user_role($wp_user->ID);
         }
 
         // do LDAP group mapping if needed
@@ -338,18 +342,19 @@
         }
 
         // optionally store the password into the wordpress database
-        if (authLdap_get_option('CachePW')) {
-            $user_info['user_pass'] = wp_hash_password($password);
-        } else {
+        if (! authLdap_get_option('CachePW')) {
             // clear the password
-            $user_info['user_pass'] = '';
+            $password = '';
+        }
+        if ( ! isset($wp_user->ID) || ! wp_check_password( $password, $wp_user->data->user_pass, $wp_user->ID) ) {
+            $user_info['user_pass'] = $password;
         }
 
         // add uid if user exists
-        if ($uid) {
+        if (isset($wp_user->ID)) {
             // found user in the database
             authLdap_debug('The LDAP user has an entry in the WP-Database');
-            $user_info['ID'] = $uid;
+            $user_info['ID'] = $wp_user->ID;
             unset ($user_info['display_name'], $user_info['nickname']);
             $userid = wp_update_user($user_info);
         } else {
@@ -383,33 +388,6 @@
     }
 }
 
-/**
- * Get user's user id
- *
- * Returns null if username not found
- *
- * @param string $username username
- * @param string user id, null if not found
- */
-function authLdap_get_uid($username)
-{
-    global $wpdb;
-
-    // find out whether the user is already present in the database
-    $uid = $wpdb->get_var(
-        $wpdb->prepare(
-            "SELECT ID FROM {$wpdb->users} WHERE user_login = %s",
-            $username
-        )
-    );
-    if ($uid) {
-        authLdap_debug("Existing user, uid = {$uid}");
-        return $uid;
-    } else {
-        return  null;
-    }
-}
-
 /**
  * Get the user's current role
  *
</code></pre>
